### ISSUE TITLE
Must be a Union job

### ISSUE THREAD

**Issue by slammingprogramming** [malforge/malforge.github.io#1]
**Six months** and the site is _still_ under construction?

**Must be a Union job.**

_But,_ on a more serious note: if you don't have the time, and you'd like me to help out with building out the site for you for GitHub Pages, let me know in this Issue, and I will happily help out there for you, just let me know what it is you are wanting and I'll make it happen and submit the PR attached to this issue. If you're all good, feel free to simply close the issue.

Thanks for your time and your awesome work on MDK and for advancing Space Engineering for centuries to come!

**Comment by malware-dev** [comment]
I'm not gonna lie

I'd half forgotten I'd set this up 😅 

I'm good. This site is to hold the autogenerated documentation currently held on the original MDK site. I just need to find time to finish the generator revamp.
